@startuml
'https://plantuml.com/sequence-diagram

actor Player
System -> Player: startProgram();
loop new game
System <- Player: startingGame();
System -> Player: askPlayerAmount();
Player --> System: playerAmount
loop no winner
Player -> System: isLoser();
loop 2..4

System -> Player : askPlayerName();
Player --> System: name
System -> System: createPlayer

end
loop  2..4
System -> Player: turn();
Player --> System: void();
end

end

end
@enduml